### ISSUE TITLE
Study OSCAR 

### ISSUE THREAD

**Issue by manuparra** [AlvaroRodriguezGallardo/src-brokering#13]
Study and discuss OSCAR: https://oscar.grycap.net/

**Comment by manuparra** [comment]
And the repo:
https://github.com/grycap/oscar

**Comment by manuparra** [comment]
Create a folder named /docs/OSCAR/README.md where we will have our docs about OSCAR.

**Comment by manuparra** [comment]
How to install:
- Install `k9s`
- First install KIND - https://kind.sigs.k8s.io/
- Use the next file to deploy kind:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
- role: worker
```
- Run `kind create  cluster --config oscar.yaml`  (to delete: `kind delete  clusters kind`)
- Check if okay: `kubectl get pods -A`
- Then, apply Ingress-ngix (*READ more on that)*: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml`
- Previously install `kubectl` tool
- Install on the `k8s` the storage driver: kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
- Check if storage is ready: `kubectl get storageClass` and `kubectl -n local-path-storage logs -f -l app=local-path-provisioner`
- Install MinIO: `curl https://raw.githubusercontent.com/minio/docs/master/source/extra/examples/minio-dev.yaml -O` and then follow the steps here: https://min.io/docs/minio/kubernetes/upstream/index.html?ref=docs-redirect 
- Once MINIO is installed, check the pods's status: `kubectl get pods -A` you have to see: all pods are `Running`.
-
